"""
PlatformIO pre-build script: generate src/network/BuildStamp.h.

X4_BUILD_STAMP is the firmware's user-visible version (yyyyMMdd.HHmm, UTC). The
reader shows it in Settings and reports it to the companion app, which compares
it with firmware.json on the update page; stamps sort in build order as strings.

It lives in a generated header rather than a -D flag so that only the few files
including it recompile when it changes, instead of the whole tree.

Set X4_BUILD_STAMP in the environment to pin a value (reproducible builds, or
re-building a published version); otherwise the current UTC time is used.
"""

import os
import re
import sys
import time


def write_build_stamp(project_dir):
    stamp = os.environ.get('X4_BUILD_STAMP') or time.strftime('%Y%m%d.%H%M', time.gmtime())
    if not re.fullmatch(r'\d{8}\.\d{4}', stamp):
        sys.exit(f'build_stamp.py: X4_BUILD_STAMP must look like yyyyMMdd.HHmm, got {stamp!r}')

    path = os.path.join(project_dir, 'src', 'network', 'BuildStamp.h')
    content = (
        '#pragma once\n'
        '// Generated by scripts/build_stamp.py -- do not edit.\n'
        f'#define X4_BUILD_STAMP "{stamp}"\n'
    )
    try:
        with open(path, encoding='utf-8') as f:
            unchanged = f.read() == content
    except OSError:
        unchanged = False
    # Rewritten only on change, so an unchanged stamp does not touch the mtime
    # and trigger a recompile of the files that include it.
    if not unchanged:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
    print(f'X4 build stamp: {stamp}')


# PlatformIO/SCons entry point -- Import and env are SCons builtins injected at
# runtime. Run directly with Python, it writes the header for this checkout.
try:
    Import('env')                             # noqa: F821  # type: ignore[name-defined]
    write_build_stamp(env['PROJECT_DIR'])     # noqa: F821  # type: ignore[name-defined]
except NameError:
    write_build_stamp(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
